import React, { useEffect, useState } from 'react';
import Head from 'next/head';
import { useRouter } from 'next/router';
import { PostConfig } from '../api/blog/posts/database/post.interface';
import { FormSendPost } from '../../components/Mains/blogLanding/utils/FormSendPost';
import { Modal } from '../../utils/portals/modalPortal';
import { usePortalProvider } from '../../utils/providers/modalProvider';
import { PageLoader } from '../../components/Layout/Spiners&Loaders/PageLoader';
import { BlogLanding } from '../../components/Mains/blogLanding/BlogLanding';


export default function Blog() {
    const { modalSwitch, setModalSwitch } = usePortalProvider();
    const router = useRouter();
    const [postIdData, setPostIdData] = useState<PostConfig>({} as PostConfig);
    const [postsList, setPostsList] = useState<PostConfig[]>([]);

    console.log(router)
    useEffect(() => {
        let mounted = true;

        const fetchPostsData = async () => {
            const id = router.asPath.split('/').pop();
            if (typeof id === 'string') {
                if (mounted) {
                    const response = await fetch('/api/blog/posts');
                    const data = await response.json();
                    const filteredData: PostConfig = await data.filter((post: any) => post.id === id)[0];
                    console.log(filteredData)
                    setPostIdData(filteredData);
                }
            }
        };

        const fetchAllPostsData = async () => {
            const response = await fetch('/api/blog/posts');
            const data = await response.json();
            setPostsList(data);
        };

        fetchPostsData();
        /*  fetchAllPostsData(); */

        return () => {
            mounted = false;
        };

    }, [router.asPath, postsList]);

    return (
        <>
            <Head>
                <title>Blog</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
                {
                    postIdData ? <>
                        <BlogLanding
                            title={postIdData?.title}
                            subtitle={postIdData?.subtitle}
                            img={
                                {
                                    src: postIdData.img?.src,
                                    alt: postIdData.img?.alt
                                }
                            }
                            description={postIdData?.description}
                            comments={postIdData?.comments}
                        />
                        <button className='blog-post__button' onClick={() => { setModalSwitch(!modalSwitch) }}>enviar</button>
                        {!!modalSwitch && (
                            <Modal>
                                <FormSendPost />
                            </Modal>
                        )}
                    </> : null
                }
        </>
    )
}