import Head from 'next/head';
import { memo, lazy } from 'react';
import { AboutMeClientDataProps } from '../utils/dataConfigWorkflow.interfaces';
import { AboutMeConfig, CmsDataConfig } from './api/customCMS/interfaces';
import { getCMSData } from '../utils/providers/requests/homeCB';


const AboutMeSection = lazy(() => import('../components/Mains/aboutMeSection/AboutMeSection'));

export default memo(function AboutMe({ aboutMe }: AboutMeClientDataProps) {

    return (
        <>
            <Head>
                <title>About Me</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            {
                aboutMe ? <AboutMeSection aboutMe={aboutMe} /> : null
            }
        </>
    );
});

interface AboutMeServerDataProps {
    props: {
        aboutMe: AboutMeConfig | null;
    }
}

export async function getServerSideProps(): Promise<AboutMeServerDataProps> {
    try {
      const cmsData: CmsDataConfig = await getCMSData();
      const aboutMe = cmsData.aboutMe;
      return {
        props: {
          aboutMe
        }
      };
    } catch (error) {
      console.error("Error al obtener los datos del CMS:", error);
      return {
        props: {
          aboutMe: null
        }
      };
    }
  }