import { memo, lazy, Suspense } from 'react';
import Head from 'next/head';

import { getCMSData } from '../utils/providers/requests/homeCB';
import { AboutMeServerDataProps } from '../utils/dataConfigWorkflow.interfaces';
import { UseCmsDataHome } from '../utils/providers/cmsDataProvider';
import { useLayoutProvider } from '../utils/providers/layOutContext';

const AboutMeSection = lazy(() => import('../components/Mains/aboutMeSection/AboutMeSection').then(({ AboutMeSection }) => ({ default: AboutMeSection })));

export default memo(function AboutMe({ aboutMe }: AboutMeServerDataProps) {

    const { pageClass } = UseCmsDataHome();
    const {pageLoader, header,  footer} = useLayoutProvider();

    return (
        <>
            <Head>
                <title>About Me</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Suspense fallback={pageLoader}>
                <div className={pageClass}>
                    {header}
                    <main className="aboutMe">
                        <AboutMeSection
                            aboutMe={aboutMe}
                        />
                    </main>
                    {footer}
                </div>
            </Suspense>
        </>
    );
});

export async function getServerSideProps(): Promise<{ props: AboutMeServerDataProps }> {

    const CmsData = await getCMSData();
    const aboutMe = CmsData?.aboutMe

    return { props: { aboutMe } };
}