import React, { useEffect, useState } from 'react';
import Head from 'next/head';
import { PageLoader } from '../components/atoms/Spiners&Loaders/PageLoader';
import { Header } from '../components/molecules/Headers/Header';
import { Footer } from '../components/molecules/Footers/Footer';
import { useCmsDataHome } from '../providers/cmsDataProvider';

export default function Blog() {
    const { pageClass } = useCmsDataHome();
    const [showStarterPage, setShowStarterPage] = useState<boolean>(true);

    useEffect(() => {
        const timerId = setTimeout(() => {
            setShowStarterPage(!showStarterPage);
        }, 3500);

        // Return a function to clear the timer before the component is unmounted.
        return () => {
            clearTimeout(timerId);
        }
    }, []);

    return (
        <>
            <Head>
                <title>Blog</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            {
                showStarterPage ? (
                    <PageLoader />
                ) : (
                    <body className={pageClass}>
                        <Header />
                        <div>home</div>
                        <Footer />
                    </body>
                )
            }
        </>
    )
}

