import React from 'react'
import Head from 'next/head'
import { useCmsDataHome } from '../providers/cmsDataProvider';
import { ContactMeSection } from '../components/molecules/Mains/ContactMeSection'

export default function ContactMe() {
    const { pageClass } = useCmsDataHome();

    return (
        <>
            <Head>
                <title>Contact Me</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <body className={pageClass}>
                <ContactMeSection />
            </body>
        </>
    )
}