import React, { useEffect, useState } from 'react';
import Head from 'next/head';
import { Inter } from '@next/font/google';
import { StarterApp } from '../components/atoms/Spiners&Loaders/StarterApp';
import { Header } from '../components/molecules/Headers/Header';
import { HomeBanner } from '../components/molecules/Banners/MainBanner';
import { Footer } from '../components/molecules/Footers/Footer';
import { useCmsDataHome } from '../providers/cmsDataProvider';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
    const { pageClass } = useCmsDataHome()
    const [showStarterApp, setShowStarterApp] = useState<boolean>(true);

    useEffect(() => {
        const timerId = setTimeout(() => {
            setShowStarterApp(!showStarterApp);
        }, 6500);

        // Return a function to clear the timer before the component is unmounted.
        return () => {
            clearTimeout(timerId);
        }
    }, []);

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            {
                showStarterApp ? (
                    <StarterApp />
                ) : (
                    <body className={pageClass}>
                        <Header />
                        <main className="main-home">
                            <HomeBanner />
                        </main>
                        <Footer />
                    </body>
                )
            }
        </>
    )
}
