import React from 'react';
import Head from 'next/head';
import { Inter } from '@next/font/google';
import { Header } from '../components/molecules/Headers/Header';
import { HomeBanner } from '../components/molecules/Banners/MainBanner';
import { Footer } from '../components/molecules/Footers/Footer';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <body className="HOME-PAGE">
                <Header />
                <main className="main-home">
                <HomeBanner />
                </main>
                <Footer />    
            </body>
            
        </>
    )
}
