import React from 'react'
import Head from 'next/head'
import { useCmsDataHome } from '../providers/cmsDataProvider';
import { PortfolioSection } from '../components/molecules/Mains/PortfolioSection'

export default function Portfolio() {
	const {pageClass} = useCmsDataHome()
	return (
		<>
			<Head>
				<title>Portfolio</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<body className={pageClass}>
				<PortfolioSection />
			</body>
		</>
	)
}