import React, { memo, useEffect, useState } from 'react';
import Head from 'next/head';
import { PortfolioServicesServerDataProps } from '../utils/dataConfigWorkflow.interfaces';
import { UseCmsDataHome } from '../utils/providers/cmsDataProvider';
import { PageLoader } from '../components/Spiners&Loaders/PageLoader';
import { Header } from '../components/Layout/Headers/Header';
import { PortfolioSection } from '../components/Mains/portfolio/PortfolioSection';
import { Footer } from '../components/Layout/Footers/Footer';
import { getCMSData } from '../utils/providers/requests/homeCB';


export default function Portfolio({portfolio}: PortfolioServicesServerDataProps) {
    
    const { pageClass } =  UseCmsDataHome();
    
    const [showStarterPage, setShowStarterPage] = useState<boolean>(true);

    useEffect(() => {
        const timerId = setTimeout(() => {
            setShowStarterPage(!showStarterPage);
        }, 3500);

        // Return a function to clear the timer before the component is unmounted.
        return () => {
            clearTimeout(timerId);
        }
    }, []);

    return (
        <>
            <Head>
                <title>Portfolio</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            {
                showStarterPage ? (
                    <PageLoader />
                ) : (
                    <body className={pageClass}>
                        <Header />
                        <main className="portfolio">
                            <PortfolioSection 
                                portfolio={portfolio}
                            />
                        </main>
                        <div className="AtomContainer">
                            <div className="atomP">
                                <div className="electronP" />
                                <div className="electronP" />
                                <div className="electronP" />
                            </div>
                        </div>
                        <Footer />
                    </body>
                )
            }
        </>
    )
}

export async function getServerSideProps(): Promise<{props: PortfolioServicesServerDataProps}> {
    
    const CmsData = await getCMSData();    
    const portfolio = CmsData?.portfolio

    return {props: { portfolio }};
}

export const MemoizedAboutMe = memo(Portfolio);