import React, { memo, useEffect, useState } from 'react';
import Head from 'next/head'
import { UseCmsDataHome } from '../utils/providers/cmsDataProvider';
import { PortfolioSectionProps } from '../utils/mainPages.interfaces';
import { PageLoader } from '../components/Spiners&Loaders/PageLoader';
import { Header } from '../components/Layout/Headers/Header';
import { ServicesWCFUSection } from '../components/Mains/ServicesWCFU/ServicesWCFUSection';
import { Footer } from '../components/Layout/Footers/Footer';


interface ServicesProps {
    data: PortfolioSectionProps;
}

export default function Services({data}: ServicesProps) {

    const [showStarterPage, setShowStarterPage] = useState<boolean>(true);

    useEffect(() => {
        const timerId = setTimeout(() => {
            setShowStarterPage(!showStarterPage);
        }, 3500);

        // Return a function to clear the timer before the component is unmounted.
        return () => {
            clearTimeout(timerId);
        }
    }, []);

    return (
        <>
            <Head>
                <title>Services</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            {
                showStarterPage ? (
                    <PageLoader />
                ) : (
                    <body className={data.pageClass}>
                        <Header />
                        <main className='services'>
                            <ServicesWCFUSection 
                                portfolio={data.portfolio}
                            />
                        </main>
                        <Footer />
                    </body>
                )
            }
        </>
    )
}

export async function getServerSideProps() {
    
    const { pageClass, CmsData } = await UseCmsDataHome();
    const { portfolio } = CmsData;

    return {
        props: {
            pageClass,
            portfolio
        }
    }
}

export const MemoizedAboutMe = memo(Services);