import React from 'react'
import Head from 'next/head'
import { useCmsDataHome } from '../providers/cmsDataProvider';

export default function Services() {
    const { pageClass } = useCmsDataHome();

    return (
        <>
            <Head>
                <title>Services</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <body className={pageClass}>
                <div>home</div>
            </body>
        </>
    )
}

