import React, { lazy, memo, Suspense } from 'react';
import Head from 'next/head'

import { UseCmsDataHome } from '../utils/providers/cmsDataProvider';
import { PageLoader } from '../components/Layout/Spiners&Loaders/PageLoader';
import { LayOut } from '../components/Layout/LayOut';
import { PortfolioConfig } from './api/customCMS/interfaces';
import { useLocalStorageData } from '../utils/hooks/getLocalStorageData';

const ServicesWCFUSection = lazy(() => import('../components/Mains/ServicesWCFU/ServicesWCFUSection').then(({ ServicesWCFUSection }) => ({ default: ServicesWCFUSection })));

export default memo(function Services() {

    const { pageClass } = UseCmsDataHome();
    const [portfolio] = useLocalStorageData<PortfolioConfig>("CmsData", "portfolio");

    return (
        <>
            <Head>
                <title>Services</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Suspense fallback={<PageLoader />}>
                <div className={pageClass}>
                    <LayOut headerSimple={true} mainClass={`services`}>
                        {portfolio ? <ServicesWCFUSection portfolio={portfolio} /> : null}
                    </LayOut>
                </div>
            </Suspense>
        </>
    );
});